# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Islectl < Formula
  desc ""
  homepage "https://github.com/islandora-devops/islectl"
  version "0.9.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.9.14/islectl_Darwin_x86_64.tar.gz"
      sha256 "da8b5bde0b660501a7de5bb396a05b9ef16ecd813f7632e6ee46007a05847d4b"

      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.9.14/islectl_Darwin_arm64.tar.gz"
      sha256 "de122ff83a2799cda475fb15d10f6a989a152e8f40fa944febda04cbcd70721d"

      def install
        bin.install "islectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.9.14/islectl_Linux_x86_64.tar.gz"
      sha256 "bcedcbad818d56d9d7278adef229720012e8c3c4991e9a325c22cfa629f9d288"
      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.9.14/islectl_Linux_arm64.tar.gz"
      sha256 "47b0df3670d179db6fa91e7251b96081394caafe27be7b46400e9ad2e19d18ef"
      def install
        bin.install "islectl"
      end
    end
  end
end
