# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Islectl < Formula
  desc ""
  homepage "https://github.com/islandora-devops/islectl"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.6/islectl_Darwin_x86_64.tar.gz"
      sha256 "ec8858bd3114789b0a1b1bb46d0306770c576e277436c7849aeca943e09db6cc"

      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.6/islectl_Darwin_arm64.tar.gz"
      sha256 "969ef407140aa0620258fa262fcda3756e16715d29d9cea28e251f2e5364017d"

      def install
        bin.install "islectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.6/islectl_Linux_x86_64.tar.gz"
      sha256 "35a0f8cc4e76515fb33a0adb1a54658ad29a671bcfcfc5ac58236819df65429b"
      def install
        bin.install "islectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Islandora-Devops/islectl/releases/download/0.0.6/islectl_Linux_arm64.tar.gz"
      sha256 "b40b1cd263647b6508a239ae867ded437aba046ee4b793d97aeba7a416c2965e"
      def install
        bin.install "islectl"
      end
    end
  end
end
